/// <reference types="vite/client" />

declare module 'virtual:convyx-icons' {
  import type { ComponentType, SVGProps } from 'react';

  /** Generated by the `convyx:icons` plugin from every manifest's `icon` field. */
  export const icons: Record<
    string,
    ComponentType<SVGProps<SVGSVGElement> & { strokeWidth?: number }> | undefined
  >;
}
